CREATE TABLE T_CLIENTE(

	ID_CLIENTE INTEGER, -- PRIMARY KEY /*
	CPF VARCHAR2(11)UNIQUE , 
	NM_COMPLETO VARCHAR2(100) NOT NULL,
	SEXO VARCHAR(1) NOT NULL,
	ENDERECO VARCHAR2(150) NOT NULL,
	DT_NASCIMENTO DATE,
	
	CONSTRAINT CK_SEXO CHECK(SEXO IN ('f','m','i')),
	CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE)
	
	);

CREATE TABLE T_PECAS(

	ID_PECAS INTEGER, -- PRIMARY KEY/*
	NM_PECAS VARCHAR2(100) UNIQUE,
	LOCAL_PECA VARCHAR2(100) NOT NULL,
	PRECO_COMPRA NUMBER NOT NULL,
	PRECO_VENDA NUMBER NOT NULL,
	
	CONSTRAINT PK_ID_PECAS PRIMARY KEY (ID_PECAS)

	);

CREATE TABLE T_OFICINAS(

	ID_OFICINAS INTEGER, --PRIMARY KEY /*
	ENDERECO VARCHAR2(150), 
	TELEFONE VARCHAR2(13)UNIQUE ,
	QTD_FUNCIONARIOS INTEGER NOT NULL,
	NM_OFICINA VARCHAR2(100)NOT NULL,
	
	CONSTRAINT PK_ID_OFICINAS PRIMARY KEY (ID_OFICINAS)

);

CREATE TABLE T_FUNCIONARIO(

	ID_FUNCIONARIO INTEGER, -- PRIMARY KEY/*
	NM_COMPLETO VARCHAR2(100),
	SEXO VARCHAR(1),
	DT_NASCIMENTO DATE NOT NULL,
	SALARIO NUMBER  NOT NULL,
	FUNCAO VARCHAR2(100) NOT NULL,
	CPF VARCHAR2 (11)UNIQUE,
	
	CONSTRAINT CK_SEXO CHECK(SEXO IN ('f','m','i')),
	
	CONSTRAINT PK_ID_FUNCIONARIO PRIMARY KEY (ID_FUNCIONARIO)
	
);


CREATE TABLE T_PLANOS(

	ID_PLANOS INTEGER, -- PRIMARY KEY/*
	NM_PLANO VARCHAR2(100) NOT NULL,
	VALOR NUMBER  NOT NULL,
	TIPO_PLANOS VARCHAR2(100),
	
	CONSTRAINT PK_ID_PLANOS PRIMARY KEY (ID_PLANOS),
	
	--CHAVE ESTRANGEIRA > ID_CLIENTE/*

	T_CLIENTE_ID_CLIENTE INTEGER,
		
	CONSTRAINT FK_T_CLIENTE_ID_CLIENTE 
	FOREIGN KEY (T_CLIENTE_ID_CLIENTE)
	REFERENCES T_CLIENTE(ID_CLIENTE)
	 	
);



CREATE TABLE T_VEICULO(

	PLACA VARCHAR2(7), --PRIMARY KEY/*
	MARCA VARCHAR2(100)NOT NULL,
	MODELO VARCHAR2(100)NOT NULL,
	ANO_FABRICACAO DATE NOT NULL,
	
	CONSTRAINT PK_PLACA PRIMARY KEY (PLACA),
	
	-- CHAVE ESTRANGEIRA >ID_CLIENTE/*

	T_CLIENTE_ID_CLIENTE INTEGER,
	
	CONSTRAINT FK_T_CLIENTE_ID_CLIENTE 
	FOREIGN KEY (T_CLIENTE_ID_CLIENTE)
	REFERENCES T_CLIENTE(ID_CLIENTE)

	);

CREATE TABLE T_ORCAMENTO( 

	ID_ORCAMENTO INTEGER, --PRIMARY KEY /*
	PRECO NUMBER NOT NULL,
	CUSTO NUMBER NOT NULL,
	
	CONSTRAINT PK_ID_ORCAMENTO PRIMARY KEY (ID_ORCAMENTO),
	
	-- CHAVE ESTRANGEIRA > PLACA/*
	
	T_VEICULO_PLACA VARCHAR2(7),
	
	CONSTRAINT FK_T_VEICULO_PLACA
	FOREIGN KEY (T_VEICULO_PLACA)
	REFERENCES T_VEICULO(PLACA)

	);

DROP TABLE T_ORCAMENTO;
DROP TABLE T_VEICULO;
DROP TABLE T_PLANOS;
DROP TABLE T_FUNCIONARIO;
DROP TABLE T_OFICINA;
DROP TABLE T_PECAS;
DROP TABLE T_CLIENTES;

